[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd examples/research && npx @langchain/langgraph-cli dev --host 0.0.0.0 --port ${PORT:-8080}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
